application:
  input:
    FragPipe-RESOURCE:
    - bfabric@fgcz-data.uzh.ch://home/bfabric/slurmworker/log//workunitid-275727_resourceid-2119092.out
    - bfabric@fgcz-data.uzh.ch://home/bfabric/slurmworker/log//workunitid-275727_resourceid-2119092.err
    - bfabric@fgcz-ms.uzh.ch://srv/www/htdocs//p27640/bfabric/Proteomics/FragPipe-RESOURCE/2022/2022-03/2022-03-09/workunit_275727/2119092.zip
  output:
  - bfabric@fgcz-ms.uzh.ch:/srv/www/htdocs/p27640/bfabric/Proteomics/SAINTexpress-Fragpipe/2022/2022-03/2022-03-14//workunit_275883//2120853.zip
  parameters:
    BFDRsignificance: '0.1'
    FCthreshold: '4'
    SpcInt: Spectral Count
    datasetId: '42003'
    memory: 1G
    nodelist: fgcz-r-033
    partition: prx
  protocol: scp
job_configuration:
  executable: /home/bfabric/slurmworker/bin/fgcz_slurm_SaintExpress_prolfqua.bash
  external_job_id: 108728
  fastasequence: '>sp|P22629|SAV_STRAV Streptavidin OS=Streptomyces avidinii OX=1895
    PE=1 SV=1

    MRKIVVAAIAVSLTTVSITASASADPSKDSKAQVSAAEAGITGTWYNQLGSTFIVTAGAD

    GALTGTYESAVGNAESRYVLTGRYDSAPATDGSGTALGWTVAWKNNYRNAHSATTWSGQY

    VGGAEARINTQWLLTSGTTEANAWKSTLVGHDTFTKVKPSAASIDAAKKAGVNNGNPLDA

    VQQ

    >Biognosys|iRT-Kit_WR_fusion

    LGGNEQVTRYILAGVENSKGTFIIDPGGVIRGTFIIDPAAVIRGAGSSEPVTGLDAKTPVISGGPYEYRVEATFGVDESNAKTPVITGAPYEYRDGLDAASYYAPVRADVTPADFSEWSKLFLQFGAQGSPFLK

    >sp|P42212|GFP_AEQVI Green fluorescent protein OS=Aequorea victoria OX=6100 GN=GFP
    PE=1 SV=1

    MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL

    VTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLV

    NRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLAD

    HYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK

    >tr|O66837|O66837_AQUAE Biotin--[biotin carboxyl-carrier protein] ligase OS=Aquifex
    aeolicus (strain VF5) OX=224324 GN=birA PE=1 SV=1

    MFKNLIWLKEVDSTQERLKEWNVSYGTALVADRQTKGRGRLGRKWLSQEGGLYFSFLLNP

    KEFENLLQLPLVLGLSVSEALEEITEIPFSLKWPNDVYFQEKKVSGVLCELSKDKLIVGI

    GINVNQREIPEEIKDRATTLYEITGKDWDRKEVLLKVLKRISENLKKFKEKSFKEFKGKI

    ESKMLYLGEEVKLLGEGKITGKLVGLSEKGGALILTEEGIKEILSGEFSLRRS'
  input:
    FragPipe-RESOURCE:
    - resource_id: 2119094
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2119094
    - resource_id: 2119093
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2119093
    - resource_id: 2119092
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2119092
  inputdataset: null
  order_id: 27640
  output:
    protocol: scp
    resource_id: 2120853
    ssh_args: -o StrictHostKeyChecking=no -2 -l bfabric -x
  project_id: null
  stderr:
    protocol: file
    resource_id: 2120854
    url: /home/bfabric/slurmworker/log/workunitid-275883_resourceid-2120853.err
  stdout:
    protocol: file
    resource_id: 2120855
    url: /home/bfabric/slurmworker/log/workunitid-275883_resourceid-2120853.out
  workunit_id: 275883
  workunit_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=275883

