application:
  input:
    MaxQuant_textfiles:
    - bfabric@fgcz-data.uzh.ch://home/bfabric/slurmworker/log//workunitid-272962_resourceid-2062292.out
    - bfabric@fgcz-data.uzh.ch://home/bfabric/slurmworker/log//workunitid-272962_resourceid-2062292.err
    - bfabric@fgcz-ms.uzh.ch://srv/www/htdocs//p26696/bfabric/Proteomics/MaxQuant_textfiles/2021/2021-12/2021-12-16/workunit_272962/2062292.zip
  output:
  - bfabric@fgcz-ms.uzh.ch:/srv/www/htdocs/p26696/bfabric/Proteomics/Compare_two_or_more_Groups_MaxQuant/2022/2022-02/2022-02-11//workunit_274587//2101385.zip
  parameters:
    1|datasetId: '41535'
    2|Aggregation: medpolish
    3|Normalization: robscale
    4|Difference_threshold: '2'
    5|FDR_threshold: '0.1'
    6|remConDec: 'true'
    7|REVpattern: ^REV__
    8|CONpattern: ^CON__|^zz
    memory: 2G
    nodelist: fgcz-r-033
    partition: prx
  protocol: scp
job_configuration:
  executable: /home/bfabric/slurmworker/bin/fgcz_slurm_Compare2Grp_MQ_prolfqua.bash
  external_job_id: 106114
  fastasequence: ''
  input:
    MaxQuant_textfiles:
    - resource_id: 2062294
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2062294
    - resource_id: 2062293
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2062293
    - resource_id: 2062292
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2062292
  inputdataset: null
  order_id: 26696
  output:
    protocol: scp
    resource_id: 2101385
    ssh_args: -o StrictHostKeyChecking=no -2 -l bfabric -x
  project_id: 23582
  stderr:
    protocol: file
    resource_id: 2101386
    url: /home/bfabric/slurmworker/log/workunitid-274587_resourceid-2101385.err
  stdout:
    protocol: file
    resource_id: 2101387
    url: /home/bfabric/slurmworker/log/workunitid-274587_resourceid-2101385.out
  workunit_id: 274587
  workunit_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=274587

