application:
  input:
    MaxQuant_textfiles:
    - bfabric@fgcz-ms.uzh.ch://srv/www/htdocs//p26696/bfabric/Proteomics/MaxQuant_textfiles/2021/2021-12/2021-12-16/workunit_272962/2062292.zip
  output:
  - bfabric@fgcz-ms.uzh.ch:/srv/www/htdocs/p3000/bfabric/Proteomics/Compare_2grp_MQ/2022/2022-01/2022-01-07//workunit_273293//2071933.zip
  parameters:
    FDRthreshold: '0.1'
    datasetId: '41499'
    memory: 2G
    nodelist: fgcz-r-033
    partition: prx
  protocol: scp
job_configuration:
  executable: /home/bfabric/slurmworker/bin/fgcz_slurm_Compare2Grp_MQ_prolfqua.bash
  external_job_id: 103267
  fastasequence: ''
  input:
    MaxQuant_textfiles:
    - resource_id: 2062292
      resource_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?id=2062292
  inputdataset: null
  order_id: null
  output:
    protocol: scp
    resource_id: 2071933
    ssh_args: -o StrictHostKeyChecking=no -2 -l bfabric -x
  project_id: 3000
  stderr:
    protocol: file
    resource_id: 2071934
    url: /home/bfabric/slurmworker/log/workunitid-273293_resourceid-2071933.err
  stdout:
    protocol: file
    resource_id: 2071935
    url: /home/bfabric/slurmworker/log/workunitid-273293_resourceid-2071933.out
  workunit_id: 273293
  workunit_url: https://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=273293

